const fs = require('node:fs');
const path = require('node:path');

const screenshotsDir = path.resolve('screenshots/titles');

const screenshotFiles = fs.readdirSync(screenshotsDir);

const slugEntries = screenshotFiles.flatMap((sf) => {
	if (!sf.endsWith('.png')) {
		return [];
	}
	const sfPath = path.resolve(screenshotsDir, sf);
	const slug = path.parse(sfPath).name;

	return [`  '${slug}': true`];
});

const mapSrc = `
// auto generated by scripts/buildSlugMap.js

const slugMap: Record<string, true> = {
${slugEntries.join(',\n')}
};

export { slugMap };

`;

const slugMapPath = path.resolve('src/main/catalog/slugMap.ts');
fs.writeFileSync(slugMapPath, mapSrc);
console.log('slugMap written to', slugMapPath);
